In [39]:
# No hidden layer
import numpy as np

def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

def sigmoid_to_derivative(output):
    return output*(1 - output)

# Create input - (4x2)
X = np.array([[0,1],
             [0,1],
             [1,0],
             [1,0]])

# Create output - (4x1)
y = np.array([[0],
              [0],
              [1],
              [1]])

# Seed random number so that it won't change when re-run.
np.random.seed(1)

# Initialize weights (from -1 to 1) (2x1)
weights_0 = 2 * np.random.random((2,1)) - 1

for i in range(10000):
    # Forward propagation
    layer_0 = X
    layer_1 = sigmoid(np.dot(layer_0,weights_0))
    
    # Error
    layer_1_error = layer_1 - y
    
    # Back propagation = error * derivative(output)
    layer_1_delta = layer_1_error * sigmoid_to_derivative(layer_1)
    
    # Gradient descent
    weights_0_gradient = np.dot(layer_0.T, layer_1_delta)         # Weight1 = (First_feature_ex1 * Derivative_output_ex1) + (First_feature_ex2 * Derivative_output_ex2) + (First_feature_ex3 * Derivative_output_ex3) + ... 
                                                                  # Weight2 = (Second_feature_ex1 * Derivative_output_ex1) + (Second_feature_ex2 * Derivative_output_ex2) + (Second_feature_ex3 * Derivative_output_ex3) + ....
                                                                  # (2x1)  
    # Update weights
    weights_0 = weights_0 - weights_0_gradient

print (y)
print (layer_1)



[[0]
 [0]
 [1]
 [1]]
[[ 0.00505119]
 [ 0.00505119]
 [ 0.99494905]
 [ 0.99494905]]


In [67]:
# 2 hidden layers

import numpy as np

def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

def sigmoid_to_derivative(output):
    return output*(1 - output)

# Create input
X = np.array([[0,1],
              [0,1],
              [1,0],
              [1,0]])

# Create output
Y = np.array([[0],
              [0],
              [1],
              [1]])

# Seed random
np.random.seed(1)

# Hidden layer size
layer_1_size = 200
layer_2_size = 100

weights_0 = 2*np.random.random((2, layer_1_size)) -1
weights_1 = 2*np.random.random((layer_1_size, layer_2_size)) - 1
weights_2 = 2*np.random.random((layer_2_size, 1)) - 1

for i in range(10000):
    layer_0 = X
    layer_1 = sigmoid(np.dot(layer_0, weights_0))
    layer_2 = sigmoid(np.dot(layer_1, weights_1))
    layer_3 = sigmoid(np.dot(layer_2, weights_2))

    
    # Error
    layer_3_error = layer_3 - Y
    layer_3_delta = layer_3_error * sigmoid_to_derivative(layer_3)
    
    # Error according to weights_2
    layer_2_error = np.dot(layer_3_delta, weights_2.T)
    layer_2_delta = layer_2_error * sigmoid_to_derivative(layer_2)
    
    # Error according to weights_1
    layer_1_error = np.dot(layer_2_delta, weights_1.T)
    layer_1_delta = layer_1_error * sigmoid_to_derivative(layer_1)
    
    # Gradient descent
    weights_0_gradient = np.dot(layer_0.T, layer_1_delta)
    
    # Update weights_0
    weights_0 = weights_0 - weights_0_gradient
    
print (Y)
print (layer_3)




[[0]
 [0]
 [1]
 [1]]
[[ 0.00443338]
 [ 0.00443338]
 [ 0.9963659 ]
 [ 0.9963659 ]]


In [14]:
# 2 hidden layer
# Make it like a class

import numpy as np
np.random.seed(1)

def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

def sigmoid_to_derivative(output):
    return output * (1 - output)

class Deep_Neural_Network:
    def __init__(self):
        self.layer_1_size = 200
        self.layer_2_size = 100
        self.weights_0 = 2*np.random.random((2, self.layer_1_size)) - 1
        self.weights_1 = 2*np.random.random((self.layer_1_size, self.layer_2_size)) - 1
        self.weights_2 = 2*np.random.random((self.layer_2_size, 1)) - 1
        self.iteration = 10000
        
    
    def predict(self, X):
        layer_0 = X
        layer_1 = sigmoid(np.dot(layer_0, self.weights_0))
        layer_2 = sigmoid(np.dot(layer_1, self.weights_1))
        layer_3 = sigmoid(np.dot(layer_2, self.weights_2))
        return layer_3
    
    def train(self, X, Y):
        for i in range(self.iteration):
            layer_0 = X
            layer_1 = sigmoid(np.dot(layer_0, self.weights_0))
            layer_2 = sigmoid(np.dot(layer_1, self.weights_1))
            layer_3 = sigmoid(np.dot(layer_2, self.weights_2))
        
            # Error
            layer_3_error = layer_3 - Y
            layer_3_delta = layer_3_error * sigmoid_to_derivative(layer_3)
        
            # Back propagation - with respect to weights_2
            layer_2_error = np.dot(layer_3_delta, self.weights_2.T)
            layer_2_delta = layer_2_error * sigmoid_to_derivative(layer_2)
            
            # Back propagation - with respect to weights_1
            layer_1_error = np.dot(layer_2_delta, self.weights_1.T)
            layer_1_delta = layer_1_error * sigmoid_to_derivative(layer_1)
            
            # Gradient descent
            weights_0_gradient = np.dot(layer_0.T, layer_1_delta)
            
            # Update weights_0
            self.weights_0 = self.weights_0 - weights_0_gradient
            
neural_network = Deep_Neural_Network()

# Create input
X = np.array([[0,1],
              [0,1],
              [1,0],
              [1,0]])

# Create output
Y = np.array([[0],
              [0],
              [1],
              [1]])

# Train the network
neural_network.train(X,Y)


print (neural_network.predict(X))
print (Y)



        

[[ 0.00443318]
 [ 0.00443318]
 [ 0.99636607]
 [ 0.99636607]]
[[0]
 [0]
 [1]
 [1]]
